### ISSUE TITLE
Is it possible to open-source the manual as well?

### ISSUE THREAD

**Issue by Hanbing59** [chichengcn/gici-open#1]
The repo is awesome! Great thanks to your team for sharing such an amazing project.

Maybe because I am a newbie in this field, I found it would be greater if the manual could be more and more detailed and specific. Of course, the work should not just be left to your team, it can be shared among all players who are interested in this project. 

Therefore, I am wondering if it is possible to upload and open-source the source code of the manual instead of merely the PDF file.

Again, thanks a lot for the fabulous work done by your team!

**Comment by chichengcn** [comment]
Thanks for your affirmation. 

We will continuously optimize the documents to better serve a wider audience. But we think it is not necessary to open source the documentation. Please feel free to raise technical issues if you have any confusion about the algorithms or usages.

**Comment by Hanbing59** [comment]
Thanks for letting me know what's in your mind.
Have a nice day!
