### ISSUE TITLE
运行时星历缺失

### ISSUE THREAD

**Issue by ZiaoLiuS** [chichengcn/gici-open#12]
感谢作者您的开源，我在使用您的开源数据集1.1和1.2运行代码的过程中，程序一直显示等待星历。请问您是否遇到过此类问题。

**Comment by ZiaoLiuS** [comment]
I20230919 23:08:00.352419 10806 data_integration.cpp:301] Waiting for ephemeris. We still have 35 satellites that do not have ephemeris. Total number of satellite is 44
I20230919 23:08:00.453202 10806 data_integration.cpp:301] Waiting for ephemeris. We still have 35 satellites that do not have ephemeris. Total number of satellite is 44
I20230919 23:08:00.551285 10806 data_integration.cpp:301] Waiting for ephemeris. We still have 35 satellites that do not have ephemeris. Total number of satellite is 44
I20230919 23:08:00.655683 10806 data_integration.cpp:301] Waiting for ephemeris. We still have 35 satellites that do not have ephemeris. Total number of satellite is 44

**Comment by chichengcn** [comment]
请参考
https://github.com/chichengcn/gici-open-dataset/issues/4

**Comment by ZiaoLiuS** [comment]
我按照数据集的真值文件给出了start_time，但似乎还是缺失星历。

**Comment by ZiaoLiuS** [comment]
可以了，谢谢！

**Comment by Ganglee98** [comment]
已经把注意把开始时间改成对应的时间。结果还是有等待星历的情况，请问还有哪里需要修改吗？data1.1时间不就是2023.3.20嘛

**Comment by Ganglee98** [comment]
> 已经注意到把开始时间改成对应的时间。结果还是有等待星历的情况，请问还有哪里需要修改吗？data1.1时间不就是2023.3.20嘛

# GICI offline pseudo-real-time PPP estimation. 
stream:
  streamers:
  - streamer:
      tag: str_gnss_rov_file
      output_tags: [fmt_gnss_rov]
      type: file
      path: /home/.../Downloads/GICI/gici-open-master/data/1.1/gnss_rover.bin
  - streamer:
      tag: str_gnss_eph
      output_tags: [fmt_gnss_eph]
      type: file
      path: /home/.../Downloads/GICI/gici-open-master/data/1.1/gnss_ephemeris.bin
  - streamer:
      tag: str_gnss_ssr
      output_tags: [fmt_gnss_ssr]
      type: file
      path: /home/.../Downloads/GICI/gici-open-master/data/1.1/gnss_ssr.bin
  - streamer:
      tag: str_gnss_atx
      output_tags: [fmt_gnss_atx]
      type: file
      path: /home/.../Downloads/GICI/gici-open-master/option/igs14.atx
      enable_time_tag: false
  - streamer:
      tag: str_dcb_file
      output_tags: [fmt_dcb_file]
      type: file
      path: /home/.../Downloads/GICI/gici-open-master/option/CAS0MGXRAP_20221580000_01D_01D_DCB.BSX
      enable_time_tag: false
  - streamer:
      tag: str_solution_file
      input_tags: [fmt_solution_file]
      type: file
      path: /home/.../Downloads/GICI/gici-open-master/out_res/1.1/ppp_solution.txt
      enable_time_tag: false

  formators:
  - formator:
      io: input
      tag: fmt_gnss_rov
      type: gnss-raw
      sub_type: tersus
  - formator:
      io: input
      tag: fmt_gnss_eph
      type: gnss-rtcm-3
      start_time: 2023.03.20
  - formator:
      io: input
      tag: fmt_gnss_ssr
      type: gnss-rtcm-3
      start_time: 2023.03.20
  - formator:
      io: input
      tag: fmt_gnss_atx
      type: atx-file
  - formator:
      io: input
      tag: fmt_dcb_file
      type: dcb-file
  - formator:
      io: output
      tag: fmt_solution_file
      type: nmea 
      use_esa: true
      talker_id: GP

**Comment by 147longlong** [comment]
你好，data1.1的start_time就是2023.03.20。直观看来，您的配置文件没有问题，请核对以下几点：

1.以上内容中未含estimate，请在实际yaml中涵盖estimate。
2.确定是否出现的是星历等待问题？还是卫星数目不足问题？如果是后者，请确保gnss_ssr.bin在文件夹实际存在。
3.data2.1与1.1的start_time相同，可以将数据集替换成2.1再尝试。
4.如果以上都没有问题，请上传完整的yaml文件

**Comment by Ganglee98** [comment]
> 你好，data1.1的start_time就是2023.03.20。直观看来，您的配置文件没有问题，请核对以下几点：
> 
> 1.以上内容中未含estimate，请在实际yaml中涵盖estimate。 2.确定是否出现的是星历等待问题？还是卫星数目不足问题？如果是后者，请确保gnss_ssr.bin在文件夹实际存在。 3.data2.1与1.1的start_time相同，可以将数据集替换成2.1再尝试。 4.如果以上都没有问题，请上传完整的yaml文件

十分感谢您的回复！下面我将完整上传yaml及运行遇到的问题，请您过目。

GICI offline pseudo-real-time PPP estimation.
stream:
streamers:
- streamer:
tag: str_gnss_rov_file
output_tags: [fmt_gnss_rov]
type: file
path: /home/.../Downloads/GICI/gici-open-master/data/4.1/gnss_rover.bin
- streamer:
tag: str_gnss_eph
output_tags: [fmt_gnss_eph]
type: file
path: /home/.../Downloads/GICI/gici-open-master/data/4.1/gnss_ephemeris.bin
- streamer:
tag: str_gnss_ssr
output_tags: [fmt_gnss_ssr]
type: file
path: /home/.../Downloads/GICI/gici-open-master/data/4.1/gnss_ssr.bin
- streamer:
tag: str_gnss_atx
output_tags: [fmt_gnss_atx]
type: file
path: /home/.../Downloads/GICI/gici-open-master/option/igs14.atx
enable_time_tag: false
- streamer:
tag: str_dcb_file
output_tags: [fmt_dcb_file]
type: file
path: /home/.../Downloads/GICI/gici-open-master/option/CAS0MGXRAP_20221580000_01D_01D_DCB.BSX
enable_time_tag: false
- streamer:
tag: str_solution_file
input_tags: [fmt_solution_file]
type: file
path: /home/liyuan/Downloads/GICI/gici-open-master/out_res/4.1/ppp_solution.txt
enable_time_tag: false

formators:
- formator:
io: input
tag: fmt_gnss_rov
type: gnss-raw
sub_type: tersus
- formator:
io: input
tag: fmt_gnss_eph
type: gnss-rtcm-3
start_time: 2023.05.21
- formator:
io: input
tag: fmt_gnss_ssr
type: gnss-rtcm-3
start_time: 2023.05.21
- formator:
io: input
tag: fmt_gnss_atx
type: atx-file
- formator:
io: input
tag: fmt_dcb_file
type: dcb-file
- formator:
io: output
tag: fmt_solution_file
type: nmea
use_esa: true
talker_id: GP

replay:
enable: true
speed: 1.0
start_offset: 0.0

estimate:
- estimator:
tag: est_ppp
type: ppp
input_tags: [fmt_gnss_rov, fmt_gnss_eph, fmt_gnss_ssr, fmt_dcb_file, fmt_gnss_atx]
fmt_gnss_rov_roles: [rover]
fmt_gnss_eph_roles: [ephemeris]
fmt_gnss_ssr_roles: [ssr_ephemeris]
fmt_dcb_file_roles: [code_bias]
fmt_gnss_atx_roles: [phase_center]
output_tags: [fmt_solution_file]
output_align_tag: fmt_gnss_rov
compute_covariance: false
ppp_options:
max_window_length: 3
use_ambiguity_resolution: false
estimate_velocity: true
gnss_estimator_base_options:
use_outlier_rejection: true
max_pesudorange_error: 4.0
max_phaserange_error: 0.03
gnss_common:
min_elevation: 12.0
system_exclude: [R]
estimator_base_options:
max_iteration: 2
num_threads: 2
max_solver_time: 0.02
verbose_output: true
solver_type: dense_schur
trust_region_strategy_type: dogleg
log_intermediate_data: false
log_intermediate_data_directory: <log-directory>

logging:
enable: true
min_log_level: 0
log_to_stderr: true
file_directory: <log-directory>




Quesion:
I20230923 16:55:04.486534 19243 streamer.cpp:118] FileStreamer: Unable to load enable_time_tag. Using default instead.
I20230923 16:55:04.486573 19243 streamer.cpp:119] FileStreamer: Unable to load swap_interval. Using default instead.
I20230923 16:55:04.486585 19243 formator.cpp:314] loadStartTime: Unable to load start_time. Using default instead.
I20230923 16:55:04.489564 19243 streaming.cpp:104] str_gnss_rov_file: Unable to load buffer length! Using default instead.
I20230923 16:55:04.489581 19243 streaming.cpp:119] str_gnss_rov_file: Unable to load loop duration! Using default instead.
I20230923 16:55:04.489658 19243 streamer.cpp:118] FileStreamer: Unable to load enable_time_tag. Using default instead.
I20230923 16:55:04.489661 19243 streamer.cpp:119] FileStreamer: Unable to load swap_interval. Using default instead.
I20230923 16:55:04.492645 19243 streaming.cpp:104] str_gnss_eph: Unable to load buffer length! Using default instead.
I20230923 16:55:04.492659 19243 streaming.cpp:119] str_gnss_eph: Unable to load loop duration! Using default instead.
I20230923 16:55:04.492695 19243 streamer.cpp:118] FileStreamer: Unable to load enable_time_tag. Using default instead.
I20230923 16:55:04.492697 19243 streamer.cpp:119] FileStreamer: Unable to load swap_interval. Using default instead.
I20230923 16:55:04.495793 19243 streaming.cpp:104] str_gnss_ssr: Unable to load buffer length! Using default instead.
I20230923 16:55:04.495806 19243 streaming.cpp:119] str_gnss_ssr: Unable to load loop duration! Using default instead.
E20230923 16:55:04.495834 19243 streaming.cpp:139] Open streamer str_gnss_ssr failed!
I20230923 16:55:04.495842 19243 streamer.cpp:119] FileStreamer: Unable to load swap_interval. Using default instead.
I20230923 16:55:04.495851 19243 streaming.cpp:104] str_gnss_atx: Unable to load buffer length! Using default instead.
I20230923 16:55:04.495854 19243 streaming.cpp:119] str_gnss_atx: Unable to load loop duration! Using default instead.
I20230923 16:55:04.495862 19243 streamer.cpp:119] FileStreamer: Unable to load swap_interval. Using default instead.
I20230923 16:55:04.495867 19243 streaming.cpp:104] str_dcb_file: Unable to load buffer length! Using default instead.
I20230923 16:55:04.495869 19243 streaming.cpp:119] str_dcb_file: Unable to load loop duration! Using default instead.
I20230923 16:55:04.495877 19243 streamer.cpp:119] FileStreamer: Unable to load swap_interval. Using default instead.
I20230923 16:55:04.495882 19243 formator.cpp:921] NmeaFormator: Unable to load use_gga. Using default instead.
I20230923 16:55:04.495884 19243 formator.cpp:922] NmeaFormator: Unable to load use_rmc. Using default instead.
I20230923 16:55:04.495887 19243 formator.cpp:924] NmeaFormator: Unable to load use_esd. Using default instead.
I20230923 16:55:04.495890 19243 streaming.cpp:104] str_solution_file: Unable to load buffer length! Using default instead.
I20230923 16:55:04.495894 19243 streaming.cpp:119] str_solution_file: Unable to load loop duration! Using default instead.
I20230923 16:55:04.495968 19243 option.cpp:622] loadOptions<gici::EstimatorBaseOptions>: Unable to load force_initial_global_position. Using default instead.
I20230923 16:55:04.495980 19243 option.cpp:658] Unable to load initial_global_position. Using default instead.
I20230923 16:55:04.495988 19243 option.cpp:667] loadOptions<gici::GnssEstimatorBaseOptions>: Unable to load reject_one_outlier_once. Using default instead.
I20230923 16:55:04.495994 19243 option.cpp:670] loadOptions<gici::GnssEstimatorBaseOptions>: Unable to load max_doppler_error. Using default instead.
I20230923 16:55:04.495996 19243 option.cpp:671] loadOptions<gici::GnssEstimatorBaseOptions>: Unable to load good_observation_min_num_satellites. Using default instead.
I20230923 16:55:04.495999 19243 option.cpp:672] loadOptions<gici::GnssEstimatorBaseOptions>: Unable to load good_observation_max_gdop. Using default instead.
I20230923 16:55:04.496001 19243 option.cpp:673] loadOptions<gici::GnssEstimatorBaseOptions>: Unable to load good_observation_max_reject_ratio. Using default instead.
I20230923 16:55:04.496004 19243 option.cpp:674] loadOptions<gici::GnssEstimatorBaseOptions>: Unable to load reset_ambiguity_min_num_continuous_unfix. Using default instead.
I20230923 16:55:04.496006 19243 option.cpp:675] loadOptions<gici::GnssEstimatorBaseOptions>: Unable to load diverge_max_reject_ratio. Using default instead.
I20230923 16:55:04.496008 19243 option.cpp:676] loadOptions<gici::GnssEstimatorBaseOptions>: Unable to load diverge_min_num_continuous_reject. Using default instead.
I20230923 16:55:04.496013 19243 option.cpp:340] loadOptions<gici::GnssCommonOptions>: Unable to load min_num_satellite_redundancy. Using default instead.
I20230923 16:55:04.496016 19243 option.cpp:341] loadOptions<gici::GnssCommonOptions>: Unable to load max_gdop. Using default instead.
I20230923 16:55:04.496018 19243 option.cpp:342] loadOptions<gici::GnssCommonOptions>: Unable to load mw_slip_thres. Using default instead.
I20230923 16:55:04.496021 19243 option.cpp:343] loadOptions<gici::GnssCommonOptions>: Unable to load gf_slip_thres. Using default instead.
I20230923 16:55:04.496023 19243 option.cpp:344] loadOptions<gici::GnssCommonOptions>: Unable to load gf_sd_slip_thres. Using default instead.
I20230923 16:55:04.496026 19243 option.cpp:345] loadOptions<gici::GnssCommonOptions>: Unable to load period. Using default instead.
I20230923 16:55:04.496030 19243 option.cpp:383] Unable to load min_SNR. Using default instead.
I20230923 16:55:04.496032 19243 option.cpp:395] Unable to load receiver_pco. Using default instead.
I20230923 16:55:04.496040 19243 option.cpp:287] Unable to load gnss_error_parameter. Using default instead.
Initialized 6 streamers, 6 formaters, and 1 estimator. Running...
I20230923 16:55:04.496718 19245 code_bias.cpp:467] Input DCBs for C05 does not contain base code 2I!
I20230923 16:55:04.507606 19248 formator.cpp:1266] Input DCBs are not closed for R06
I20230923 16:55:04.507648 19248 formator.cpp:1266] Input DCBs are not closed for R10
I20230923 16:55:04.507676 19248 formator.cpp:1266] Input DCBs are not closed for R23
I20230923 16:55:04.582602 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:04.684139 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:04.780705 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:04.881848 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:04.982831 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.090140 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.181906 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.283607 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.385416 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.481448 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.581846 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.684823 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.786751 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.882258 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:05.983736 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.089787 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.185601 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.281725 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.383741 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.484127 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.585534 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.682533 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.778028 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.884797 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:06.986246 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:07.091606 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:07.183110 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:07.284510 19244 data_integration.cpp:301] Waiting for ephemeris. We still have 37 satellites that do not have ephemeris. Total number of satellite is 44
I20230923 16:55:07.394009 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:07.490679 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:07.588677 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:07.689016 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:07.783695 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:07.886189 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:07.979715 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.090219 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.189184 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.288281 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.388388 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.491186 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.585942 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.686364 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.787806 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.884464 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:08.989281 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:09.095507 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:09.182811 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!
I20230923 16:55:09.287750 19252 gnss_estimator_base.h:633] Insufficient satellites! We need at least 6 satellites, but we only have 0!

**Comment by Ganglee98** [comment]
> 你好，data1.1的start_time就是2023.03.20。直观看来，您的配置文件没有问题，请核对以下几点：
> 
> 1.以上内容中未含estimate，请在实际yaml中涵盖estimate。 2.确定是否出现的是星历等待问题？还是卫星数目不足问题？如果是后者，请确保gnss_ssr.bin在文件夹实际存在。 3.data2.1与1.1的start_time相同，可以将数据集替换成2.1再尝试。 4.如果以上都没有问题，请上传完整的yaml文件

Thanks a lot. I  use the datasets 4.1 which has the ssr data and then it works.
However, it still exists the following questions:

F20230923 17:37:30.726711 22140 marginalization_error.cpp:606] Check failed: it != parameter_block_id_to_parameter_block_info_idx_.end() trying to marginalize out unconnected parameter block id = 3534327355540504576
*** Check failure stack trace: ***
    @     0x7fa892a4d160  google::LogMessage::Fail()
    @     0x7fa892a4d0a1  google::LogMessage::SendToLog()
    @     0x7fa892a4c8be  google::LogMessage::Flush()
    @     0x7fa892a50564  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa892ef79b1  gici::MarginalizationError::marginalizeOut()
    @     0x7fa892eb7666  gici::EstimatorBase::applyMarginalization()
    @     0x7fa892dfc02c  gici::PppEstimator::marginalization()
    @     0x7fa892dfdfbf  gici::PppEstimator::estimate()
    @     0x7fa892f550df  gici::MultiSensorEstimating::processEstimator()
    @     0x7fa892f5591e  gici::MultiSensorEstimating::runBackend()
    @     0x7fa892923df4  (unknown)
    @     0x7fa892aeb609  start_thread
    @     0x7fa89275d133  clone
    @              (nil)  (unknown)
Aborted (core dumped)

Thank you again.

**Comment by 147longlong** [comment]
> > 你好，data1.1的start_time就是2023.03.20。直观看来，您的配置文件没有问题，请核对以下几点：
> > 1.以上内容中未含estimate，请在实际yaml中涵盖estimate。 2.确定是否出现的是星历等待问题？还是卫星数目不足问题？如果是后者，请确保gnss_ssr.bin在文件夹实际存在。 3.data2.1与1.1的start_time相同，可以将数据集替换成2.1再尝试。 4.如果以上都没有问题，请上传完整的yaml文件
> 
> Thanks a lot. I use the datasets 4.1 which has the ssr data and then it works. However, it still exists the following questions:
> 
> F20230923 17:37:30.726711 22140 marginalization_error.cpp:606] Check failed: it != parameter_block_id_to_parameter_block_info_idx_.end() trying to marginalize out unconnected parameter block id = 3534327355540504576 *** Check failure stack trace: *** @ 0x7fa892a4d160 google::LogMessage::Fail() @ 0x7fa892a4d0a1 google::LogMessage::SendToLog() @ 0x7fa892a4c8be google::LogMessage::Flush() @ 0x7fa892a50564 google::LogMessageFatal::~LogMessageFatal() @ 0x7fa892ef79b1 gici::MarginalizationError::marginalizeOut() @ 0x7fa892eb7666 gici::EstimatorBase::applyMarginalization() @ 0x7fa892dfc02c gici::PppEstimator::marginalization() @ 0x7fa892dfdfbf gici::PppEstimator::estimate() @ 0x7fa892f550df gici::MultiSensorEstimating::processEstimator() @ 0x7fa892f5591e gici::MultiSensorEstimating::runBackend() @ 0x7fa892923df4 (unknown) @ 0x7fa892aeb609 start_thread @ 0x7fa89275d133 clone @ (nil) (unknown) Aborted (core dumped)
> 
> Thank you again.

If you use the non-ROS interface, it is a BUG of latest version. The author will fix it a few days later. Refer to https://github.com/chichengcn/gici-open/issues/11#issuecomment-1724975468

**Comment by Ganglee98** [comment]
> > > 你好，data1.1的start_time就是2023.03.20。直观看来，您的配置文件没有问题，请核对以下几点：
> > > 1.以上内容中未含estimate，请在实际yaml中涵盖estimate。 2.确定是否出现的是星历等待问题？还是卫星数目不足问题？如果是后者，请确保gnss_ssr.bin在文件夹实际存在。 3.data2.1与1.1的start_time相同，可以将数据集替换成2.1再尝试。 4.如果以上都没有问题，请上传完整的yaml文件
> > 
> > 
> > Thanks a lot. I use the datasets 4.1 which has the ssr data and then it works. However, it still exists the following questions:
> > F20230923 17:37:30.726711 22140 marginalization_error.cpp:606] Check failed: it != parameter_block_id_to_parameter_block_info_idx_.end() trying to marginalize out unconnected parameter block id = 3534327355540504576 *** Check failure stack trace: *** @ 0x7fa892a4d160 google::LogMessage::Fail() @ 0x7fa892a4d0a1 google::LogMessage::SendToLog() @ 0x7fa892a4c8be google::LogMessage::Flush() @ 0x7fa892a50564 google::LogMessageFatal::~LogMessageFatal() @ 0x7fa892ef79b1 gici::MarginalizationError::marginalizeOut() @ 0x7fa892eb7666 gici::EstimatorBase::applyMarginalization() @ 0x7fa892dfc02c gici::PppEstimator::marginalization() @ 0x7fa892dfdfbf gici::PppEstimator::estimate() @ 0x7fa892f550df gici::MultiSensorEstimating::processEstimator() @ 0x7fa892f5591e gici::MultiSensorEstimating::runBackend() @ 0x7fa892923df4 (unknown) @ 0x7fa892aeb609 start_thread @ 0x7fa89275d133 clone @ (nil) (unknown) Aborted (core dumped)
> > Thank you again.
> 
> If you use the non-ROS interface, it is a BUG of the latest version. The author will fix it a few days later. Refer to [#11 (comment)](https://github.com/chichengcn/gici-open/issues/11#issuecomment-1724975468)

Thanks for your help.
