### ISSUE TITLE
tag文件作用以及如何跑通自己的org文件？

### ISSUE THREAD

**Issue by zhSlamer** [chichengcn/gici-open#15]
您好！感谢您出色的工作！我想请教您两个问题：
1、数据集中的tag文件有何作用？因为我删除了之后，程序便不能运行。
2、我拥有的数据是符合rtcm32协议的org文件，里面包含了观测、星历、基站数据，如何能和您的数据接口对应呢？
最后再次非常感谢您的工作！

**Comment by chichengcn** [comment]
tag里面记录了bin文件的时序信息，记录bin文件时，每写入一段bin数据，都会写入一段tag数据，记录写入该断bin数据的时间，以及这个时间对应的bin文件指针位置。如果不存在tag文件，则等效于将enable_time_tag设为false（参考手册），这种情况下，bin文件中的所有数据将在程序开始时全部读入，如果观测数据采用这种读入方式的话，会产生严重阻塞，程序可能会崩溃。

tools文件夹下有generate_tag工具，可以使用这个工具生成tag文件，然后按照正常流程运行。tool中的工具的使用方法并没有在manual中说明，不过代码形式都比较简单，应该比较容易能看懂怎么使用。

目前我们的回放方式是仿实时方式，这种方式比较有利于调试实时软件。基于用户反馈，我们也正在开发不依赖于tag的回放机制，即后处理模式，可能在未来的几个月内发布出来。

**Comment by zhSlamer** [comment]
好的，非常感谢您的回答，再次感谢您出色的工作！
