### ISSUE TITLE
想请问一下作者如果把5G融合进来组合导航是否容易实现呢？

### ISSUE THREAD

**Issue by ZHAOFEGNSHUN** [chichengcn/gici-open#18]
GNSS+5G融合定位

**Comment by ZHAOFEGNSHUN** [comment]
有没有什么具体的建议啊

**Comment by chichengcn** [comment]
这个问题有点太发散了。

你可以考虑使用松组合方式，即，将5G的定位结果输入到GICI中，使用Solution结构体将结果输入到GICI算法框架中（与GNSS到导航解输入到LC或SRR算法模块的方式相同），并仿照LC或SRR的算法模式进行程序编写。

**Comment by ZHAOFEGNSHUN** [comment]
感谢您！
