### ISSUE TITLE
想请作者看看我这个数据集存放是否正确

### ISSUE THREAD

**Issue by ZHAOFEGNSHUN** [chichengcn/gici-open#19]
![image](https://github.com/chichengcn/gici-open/assets/66624774/5421e196-9cb5-4d11-a69a-b8aab3abce1b)

**Comment by chichengcn** [comment]
你的数据呢？

**Comment by ZHAOFEGNSHUN** [comment]
不好意思因为是新手刚开始接触 看您提供的数据集中只有图像，还在纳闷gnss和imu数据在哪里。希望池博能指点一下，刚开始学真的很糊涂55555，谢谢！

**Comment by chichengcn** [comment]
从README中的下载链接下载数据。

**Comment by ZHAOFEGNSHUN** [comment]
好的好的 太谢谢您了
