### ISSUE TITLE
GNSS解算模型以及对于异常因子的处理

### ISSUE THREAD

**Issue by ZHAOFEGNSHUN** [chichengcn/gici-open#22]
池博，想请问一下本代码GNSS解算模型是用的什么方法呢？以及对于异常因子的处理是什么呢？在代码的哪个部分能看到这部分内容呢？想朝着这个方向改进一下不知是否可行~谢谢

**Comment by chichengcn** [comment]
GNSS解算模型请参考manual。

对于“异常因子的处理”能表述的再清晰些么，没太懂。

**Comment by ZHAOFEGNSHUN** [comment]
就是在增强因子图鲁棒性上是否有什么操作？或者在遇到有异常的因子的时候会进行什么操作？在思考是否可以在这方面改进一下能够提高精度。或者作者有什么好的改进的点吗？因为目前在思考有什么方法可以在您的基础上进行一些创新。感谢！

**Comment by chichengcn** [comment]
纯GNSS算法主要有三方面鲁棒性提升策略：
1. 使用鲁棒核函数
2. 基于当前历元残差的FDE
3. 基于环境开阔度和模糊度固定情况调整历元间模糊度约束

你可以在估计器的实现以及基类中找到相关代码，估计器实现对应rtk_estimator.cpp, ppp_estimator.cpp等，基类对应gnss_estimator_base.cpp和gnss_estimator_base_differential.cpp等。
