### ISSUE TITLE
得不到论文中的结果

### ISSUE THREAD

**Issue by Maybe-so** [chichengcn/gici-open#27]
您好，我在ROS下用gici跑了4.1数据集，用的是RTK-RRR解算，然后用EVO评估rtk-rrr-solution和ground-truth的绝对轨迹误差，我已确认配置文件无误，并且结果的坐标系也已经转换，但是离论文中的APE结果差很远，想请问一下论文中的APE是怎么得到的，以及可能存在哪些我没有发现的问题影响结果。

**Comment by chichengcn** [comment]
你可以看一下log文件，应该有很多WARNING和ERROR。最可能的原因是，你的电脑性能不达标，由于我们用的是仿实时回放，电脑处理不过来的话数据就会阻塞，程序会自动稀疏化数据，性能会下降。如果阻塞严重，程序可能会发散并重置。你可以降低回放速率，保证log中不要有“pending”相关字眼。

**Comment by Maybe-so** [comment]
> 你可以看一下log文件，应该有很多WARNING和ERROR。最可能的原因是，你的电脑性能不达标，由于我们用的是仿实时回放，电脑处理不过来的话数据就会阻塞，程序会自动稀疏化数据，性能会下降。如果阻塞严重，程序可能会发散并重置。你可以降低回放速率，保证log中不要有“pending”相关字眼。

好的，感谢回复
