### ISSUE TITLE
gici_main: command not found

### ISSUE THREAD

**Issue by sdjkjsdh** [chichengcn/gici-open#3]
Hi,
Thank for opensource this powerful software. And I am trying to run a demo but encounter some problems.
I think I have completed the compile successfully but still can not find the 'gici_main'.

The following is the log in the terminal after excuting the command 'make -j8'

bryan@bryan-virtual-machine:~/gici-open/build$ make -j8
[  0%] Building CXX object third_party/fast/CMakeFiles/fast.dir/src/fast_10.cpp.o
[  0%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/convgpx.c.o
[  1%] Building CXX object third_party/fast/CMakeFiles/fast.dir/src/fast_10_score.cpp.o
[  1%] Building CXX object third_party/fast/CMakeFiles/fast.dir/src/nonmax_3x3.cpp.o
[  2%] Building CXX object third_party/fast/CMakeFiles/fast.dir/src/faster_corner_10_sse.cpp.o
[  3%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/convkml.c.o
[  3%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/convrnx.c.o
[  4%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_cameras/camera_factory.cpp.o
[  5%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/datum.c.o
[  5%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/download.c.o
[  5%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_cameras/camera_geometry_base.cpp.o
[  6%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/ephemeris.c.o
[  7%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/geoid.c.o
[  7%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/gis.c.o
[  8%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/ionex.c.o
[  8%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/lambda.c.o
[  9%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/options.c.o
[  9%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/pntpos.c.o
[ 10%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/postpos.c.o
[ 10%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/ppp.c.o
[ 11%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/ppp_ar.c.o
[ 12%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/preceph.c.o
[ 12%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcvraw.c.o
[ 13%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rinex.c.o
[ 13%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rtcm.c.o
[ 14%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rtcm2.c.o
[ 14%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rtcm3.c.o
[ 15%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rtcm3e.c.o
[ 16%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rtkcmn.c.o
[ 16%] Linking CXX shared library ../../../third_party/fast/lib/libfast.so
[ 16%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rtkpos.c.o
/usr/bin/c++ -fPIC -Wall -Werror -Wno-unknown-pragmas -fpermissive -mmmx -msse -msse -msse2 -msse3 -mssse3 -O3 -fsee -fomit-frame-pointer -fno-signed-zeros -fno-math-errno -funroll-loops  -shared -Wl,-soname,libfast.so -o ../../../third_party/fast/lib/libfast.so CMakeFiles/fast.dir/src/fast_10.cpp.o CMakeFiles/fast.dir/src/fast_10_score.cpp.o CMakeFiles/fast.dir/src/nonmax_3x3.cpp.o CMakeFiles/fast.dir/src/faster_corner_10_sse.cpp.o 
[ 16%] Built target fast
[ 17%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rtksvr.c.o
[ 17%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/sbas.c.o
[ 18%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/solution.c.o
[ 18%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/stream.c.o
[ 19%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/streamsvr.c.o
[ 19%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/tides.c.o
[ 20%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/tle.c.o
[ 21%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/binex.c.o
[ 21%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/crescent.c.o
[ 22%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_cameras/camera_yaml_serialization.cpp.o
[ 23%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/javad.c.o
[ 23%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/novatel.c.o
[ 24%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/nvs.c.o
[ 24%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/rt17.c.o
[ 25%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/septentrio.c.o
[ 25%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/skytraq.c.o
[ 26%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/ss2.c.o
[ 27%] Building C object third_party/rtklib/CMakeFiles/rtklib.dir/src/rcv/ublox.c.o
[ 27%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_cameras/equidistant_fisheye_geometry.cpp.o
[ 28%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_cameras/equidistant_fisheye_projection.cpp.o
[ 28%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_cameras/ncamera.cpp.o
[ 29%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_cameras/ncamera_yaml_serialization.cpp.o
[ 29%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_cameras/omni_geometry.cpp.o
[ 29%] Linking C shared library ../../../third_party/rtklib/lib/librtklib.so
[ 29%] Built target rtklib
[ 30%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_cameras/omni_projection.cpp.o
[ 31%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_common/homography.cpp.o
[ 31%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_common/math_utils.cpp.o
[ 32%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_common/performance_monitor.cpp.o
[ 32%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_common/sample.cpp.o
[ 33%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_common/user_input_thread.cpp.o
[ 33%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_common/vision.cpp.o
[ 34%] Building CXX object third_party/rpg_vikit/vikit_common/CMakeFiles/vikit_common.dir/src/vikit_solver/robust_cost.cpp.o
[ 35%] Linking CXX shared library ../../../../third_party/rpg_vikit/vikit_common/lib/libvikit_common.so
[ 35%] Built target vikit_common
[ 36%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_common/empty.cpp.o
[ 36%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_common/frame.cpp.o
[ 37%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_direct/depth_filter.cpp.o
[ 38%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_direct/feature_alignment.cpp.o
[ 38%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_direct/depth_estimation.cpp.o
[ 39%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_direct/feature_detection.cpp.o
[ 39%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_direct/elder_zucker.cpp.o
[ 40%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_common/point.cpp.o
[ 40%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_direct/feature_detection_utils.cpp.o
[ 41%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_direct/matcher.cpp.o
[ 41%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_direct/patch_warp.cpp.o
[ 42%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/frame_handler_array.cpp.o
[ 42%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/frame_handler_base.cpp.o
[ 43%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/frame_handler_mono.cpp.o
[ 44%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/frame_handler_stereo.cpp.o
[ 44%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/imu_handler.cpp.o
[ 45%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/initialization.cpp.o
[ 45%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/io.cpp.o
[ 46%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/map.cpp.o
[ 46%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/pose_optimizer.cpp.o
[ 47%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/reprojector.cpp.o
[ 47%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo/stereo_triangulation.cpp.o
[ 48%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/rpg_common/fs.cpp.o
[ 49%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_tracker/feature_tracker.cpp.o
[ 49%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_tracker/feature_tracking_types.cpp.o
[ 50%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_tracker/feature_tracking_utils.cpp.o
[ 50%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_tracker/feature_tracking_viz.cpp.o
[ 51%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_img_align/sparse_img_align_base.cpp.o
[ 51%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_img_align/sparse_img_align.cpp.o
[ 52%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_vio_common/test_utils.cpp.o
[ 52%] Building CXX object third_party/rpg_svo/CMakeFiles/svo.dir/src/svo_vio_common/vio_common.cpp.o
[ 53%] Linking CXX shared library ../../../third_party/rpg_svo/lib/libsvo.so
[ 53%] Built target svo
[ 54%] Building CXX object CMakeFiles/gici.dir/src/utility/global_variable.cpp.o
[ 54%] Building CXX object CMakeFiles/gici.dir/src/utility/common.cpp.o
[ 55%] Building CXX object CMakeFiles/gici.dir/src/utility/node_option_handle.cpp.o
[ 56%] Building CXX object CMakeFiles/gici.dir/src/utility/option.cpp.o
[ 56%] Building CXX object CMakeFiles/gici.dir/src/utility/signal_handle.cpp.o
[ 57%] Building CXX object CMakeFiles/gici.dir/src/utility/spin_control.cpp.o
[ 57%] Building CXX object CMakeFiles/gici.dir/src/utility/transform.cpp.o
[ 58%] Building CXX object CMakeFiles/gici.dir/src/stream/data_integration.cpp.o
[ 58%] Building C object CMakeFiles/gici.dir/src/stream/format_image.c.o
[ 59%] Building C object CMakeFiles/gici.dir/src/stream/format_imu.c.o
[ 59%] Building CXX object CMakeFiles/gici.dir/src/stream/formator.cpp.o
[ 60%] Building CXX object CMakeFiles/gici.dir/src/stream/node_handle.cpp.o
[ 61%] Building CXX object CMakeFiles/gici.dir/src/stream/streamer.cpp.o
[ 61%] Building CXX object CMakeFiles/gici.dir/src/stream/streaming.cpp.o
[ 62%] Building CXX object CMakeFiles/gici.dir/src/gnss/ambiguity_common.cpp.o
[ 62%] Building CXX object CMakeFiles/gici.dir/src/gnss/ambiguity_error.cpp.o
[ 63%] Building CXX object CMakeFiles/gici.dir/src/gnss/ambiguity_resolution.cpp.o
[ 63%] Building CXX object CMakeFiles/gici.dir/src/gnss/ambiguity_resolution_differential.cpp.o
[ 64%] Building CXX object CMakeFiles/gici.dir/src/gnss/code_bias.cpp.o
[ 64%] Building CXX object CMakeFiles/gici.dir/src/gnss/dgnss_estimator.cpp.o
[ 65%] Building CXX object CMakeFiles/gici.dir/src/gnss/doppler_error.cpp.o
[ 66%] Building CXX object CMakeFiles/gici.dir/src/gnss/geodetic_coordinate.cpp.o
[ 66%] Building CXX object CMakeFiles/gici.dir/src/gnss/gnss_common.cpp.o
[ 67%] Building CXX object CMakeFiles/gici.dir/src/gnss/gnss_estimator_base.cpp.o
[ 67%] Building CXX object CMakeFiles/gici.dir/src/gnss/gnss_estimator_base_differential.cpp.o
[ 68%] Building CXX object CMakeFiles/gici.dir/src/gnss/gnss_estimator_base_logger.cpp.o
[ 68%] Building CXX object CMakeFiles/gici.dir/src/gnss/gnss_loose_estimator_base.cpp.o
[ 69%] Building CXX object CMakeFiles/gici.dir/src/gnss/gnss_types.cpp.o
[ 69%] Building CXX object CMakeFiles/gici.dir/src/gnss/phase_bias.cpp.o
[ 70%] Building CXX object CMakeFiles/gici.dir/src/gnss/phase_windup.cpp.o
[ 71%] Building CXX object CMakeFiles/gici.dir/src/gnss/phaserange_error.cpp.o
[ 71%] Building CXX object CMakeFiles/gici.dir/src/gnss/phaserange_error_dd.cpp.o
[ 72%] Building CXX object CMakeFiles/gici.dir/src/gnss/phaserange_error_sd.cpp.o
[ 72%] Building CXX object CMakeFiles/gici.dir/src/gnss/position_error.cpp.o
[ 73%] Building CXX object CMakeFiles/gici.dir/src/gnss/ppp_estimator.cpp.o
[ 73%] Building CXX object CMakeFiles/gici.dir/src/gnss/pseudorange_error.cpp.o
[ 74%] Building CXX object CMakeFiles/gici.dir/src/gnss/pseudorange_error_dd.cpp.o
[ 75%] Building CXX object CMakeFiles/gici.dir/src/gnss/pseudorange_error_sd.cpp.o
[ 75%] Building CXX object CMakeFiles/gici.dir/src/gnss/rtk_estimator.cpp.o
[ 76%] Building CXX object CMakeFiles/gici.dir/src/gnss/sdgnss_estimator.cpp.o
[ 76%] Building CXX object CMakeFiles/gici.dir/src/gnss/spp_estimator.cpp.o
[ 77%] Building CXX object CMakeFiles/gici.dir/src/gnss/velocity_error.cpp.o
[ 77%] Building CXX object CMakeFiles/gici.dir/src/imu/hmc_error.cpp.o
[ 78%] Building CXX object CMakeFiles/gici.dir/src/imu/imu_common.cpp.o
[ 78%] Building CXX object CMakeFiles/gici.dir/src/imu/imu_error.cpp.o
[ 79%] Building CXX object CMakeFiles/gici.dir/src/imu/imu_estimator_base.cpp.o
[ 80%] Building CXX object CMakeFiles/gici.dir/src/imu/nhc_error.cpp.o
[ 80%] Building CXX object CMakeFiles/gici.dir/src/imu/roll_and_pitch_error.cpp.o
[ 81%] Building CXX object CMakeFiles/gici.dir/src/imu/speed_and_bias_error.cpp.o
[ 81%] Building CXX object CMakeFiles/gici.dir/src/imu/yaw_error.cpp.o
[ 82%] Building CXX object CMakeFiles/gici.dir/src/vision/feature_handler.cpp.o
[ 82%] Building CXX object CMakeFiles/gici.dir/src/vision/feature_matcher.cpp.o
[ 83%] Building CXX object CMakeFiles/gici.dir/src/vision/feature_tracker.cpp.o
[ 83%] Building CXX object CMakeFiles/gici.dir/src/vision/homogeneous_point_error.cpp.o
[ 84%] Building CXX object CMakeFiles/gici.dir/src/vision/relative_pose_error.cpp.o
[ 85%] Building CXX object CMakeFiles/gici.dir/src/vision/visual_estimator_base.cpp.o
[ 85%] Building CXX object CMakeFiles/gici.dir/src/vision/visual_initialization.cpp.o
[ 86%] Building CXX object CMakeFiles/gici.dir/src/estimate/ceres_iteration_callback.cpp.o
[ 86%] Building CXX object CMakeFiles/gici.dir/src/estimate/error_interface.cpp.o
[ 87%] Building CXX object CMakeFiles/gici.dir/src/estimate/estimating.cpp.o
[ 87%] Building CXX object CMakeFiles/gici.dir/src/estimate/estimator_base.cpp.o
[ 88%] Building CXX object CMakeFiles/gici.dir/src/estimate/estimator_types.cpp.o
[ 88%] Building CXX object CMakeFiles/gici.dir/src/estimate/graph.cpp.o
[ 89%] Building CXX object CMakeFiles/gici.dir/src/estimate/homogeneous_point_local_parameterization.cpp.o
[ 90%] Building CXX object CMakeFiles/gici.dir/src/estimate/homogeneous_point_parameter_block.cpp.o
[ 90%] Building CXX object CMakeFiles/gici.dir/src/estimate/local_parameterization_additional_interfaces.cpp.o
[ 91%] Building CXX object CMakeFiles/gici.dir/src/estimate/marginalization_error.cpp.o
[ 91%] Building CXX object CMakeFiles/gici.dir/src/estimate/motion_detector.cpp.o
[ 92%] Building CXX object CMakeFiles/gici.dir/src/estimate/pose_error.cpp.o
[ 92%] Building CXX object CMakeFiles/gici.dir/src/estimate/pose_local_parameterization.cpp.o
[ 93%] Building CXX object CMakeFiles/gici.dir/src/estimate/pose_parameter_block.cpp.o
[ 94%] Building CXX object CMakeFiles/gici.dir/src/estimate/speed_and_bias_parameter_block.cpp.o
[ 94%] Building CXX object CMakeFiles/gici.dir/src/fusion/gnss_imu_camera_srr_estimator.cpp.o
[ 95%] Building CXX object CMakeFiles/gici.dir/src/fusion/gnss_imu_initializer.cpp.o
[ 95%] Building CXX object CMakeFiles/gici.dir/src/fusion/gnss_imu_lc_estimator.cpp.o
[ 96%] Building CXX object CMakeFiles/gici.dir/src/fusion/multisensor_estimating.cpp.o
[ 96%] Building CXX object CMakeFiles/gici.dir/src/fusion/rtk_imu_camera_rrr_estimator.cpp.o
[ 97%] Building CXX object CMakeFiles/gici.dir/src/fusion/rtk_imu_tc_estimator.cpp.o
[ 97%] Building CXX object CMakeFiles/gici.dir/src/fusion/spp_imu_camera_rrr_estimator.cpp.o
[ 98%] Building CXX object CMakeFiles/gici.dir/src/fusion/spp_imu_tc_estimator.cpp.o
[ 99%] Linking CXX shared library libgici.so
[ 99%] Built target gici
[ 99%] Building CXX object CMakeFiles/gici_main.dir/src/gici_main.cpp.o
[100%] Linking CXX executable gici_main
/usr/bin/ld: warning: libglog.so.0, needed by libgici.so, may conflict with libglog.so.1
/usr/bin/ld: CMakeFiles/gici_main.dir/src/gici_main.cpp.o: in function `YAML::Node YAML::Node::operator[]<char [8]>(char const (&) [8])':
gici_main.cpp:(.text._ZN4YAML4NodeixIA8_cEES0_RKT_[_ZN4YAML4NodeixIA8_cEES0_RKT_]+0x13e): undefined reference to `YAML::detail::node_data::convert_to_map(std::shared_ptr<YAML::detail::memory_holder> const&)'
/usr/bin/ld: libgici.so: undefined reference to `YAML::detail::node_data::empty_scalar[abi:cxx11]()'
/usr/bin/ld: ../third_party/rpg_vikit/vikit_common/lib/libvikit_common.so: undefined reference to `YAML::detail::node::m_amount'
/usr/bin/ld: ../third_party/rpg_vikit/vikit_common/lib/libvikit_common.so: undefined reference to `YAML::detail::node_data::push_back(YAML::detail::node&, std::shared_ptr<YAML::detail::memory_holder> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gici_main.dir/build.make:157: gici_main] Error 1
make[1]: *** [CMakeFiles/Makefile2:165: CMakeFiles/gici_main.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

/home/bryan/Pictures/Screenshot from 2023-07-06 23-00-59.png

![Screenshot from 2023-07-06 23-00-59](https://github.com/chichengcn/gici-open/assets/14803083/aa724956-218b-4d97-8f97-194c6269ce4b)

Could you please help tell me what I have missed and how to solve this problem?

**Comment by chichengcn** [comment]
Maybe you have installed the wrong version of yaml-cpp library. You should install it on https://github.com/jbeder/yaml-cpp, and then compile and install it. Before that, remember to uninstall your current-version yaml-cpp properly.

**Comment by chichengcn** [comment]
Maybe you have installed the wrong version of yaml-cpp library. You should download it on https://github.com/jbeder/yaml-cpp, and then compile and install it. Before that, remember to uninstall your current version yaml-cpp properly.

**Comment by sdjkjsdh** [comment]
> Maybe you have installed the wrong version of yaml-cpp library. You should download it on https://github.com/jbeder/yaml-cpp, and then compile and install it. Before that, remember to uninstall your current version yaml-cpp properly.

Thank you for the reply and the problem has been solved!

**Comment by sdjkjsdh** [comment]
![1688896644750](https://github.com/chichengcn/gici-open/assets/14803083/4724fa32-2511-45bb-8291-dadafd069d66)

But why the GICI-LIB keeps watting for ephemeris and unable to load anything?

**Comment by chichengcn** [comment]
Just ignore the INFO messages (Start with the term "I"), those are normal information. You should just care about the WARNING, ERROR, and FATAL messages.

GICI waits for sufficient ephemerides to start estimation, this process usually costs a few seconds. If the number of ephemerides is continually insufficient, you should check the "start_time" option in the RTCM formators. We stored the ephemerides in the RTCM format. Since it does not record the GPS week information, users should specify the record date to ensure correct RTCM decoding.
