### ISSUE TITLE
数据格式转换：bin to rosbag

### ISSUE THREAD

**Issue by ZoYooJy** [chichengcn/gici-open#31]
描述：通过gici_files_to_rosbag.cpp将dataset中的bin文件转换为rosbag，并以ros的形式运行代码。修改convert_rosbags.yaml中5个输入路径(bin), 5个输出路径(rosbag), 2个start_time(与goundtruth中的时间对应)
问题：只有dataset 1.1能够转换成功并正常运行，其余的output均无数据，且rviz中表现为marker status:error
![capture_20240105123502650](https://github.com/chichengcn/gici-open/assets/93439999/ef55968f-2c18-4101-8477-6e170863dc92)
![capture_20240105123527086](https://github.com/chichengcn/gici-open/assets/93439999/965f427c-a247-438e-b6dc-41e1d9ec9917)

**Comment by ZoYooJy** [comment]
请问我是忽略了某些地方导致的错误么？谢谢！！！

**Comment by chichengcn** [comment]
时间要与gici-open-dataset readme中的表格相对应，即

![image](https://github.com/chichengcn/gici-open/assets/44891397/d9d70890-fc30-477d-b832-1f659548f6bc)

**Comment by ZoYooJy** [comment]
好的，感谢回复！！！
