### ISSUE TITLE
请问为什么紧组合固定率会很低

### ISSUE THREAD

**Issue by lizhengnss** [chichengcn/gici-open#32]
池博您好，非常感谢您的开源工作，代码非常漂亮！
有个问题向您请教，我在使用RTK/INS紧组合对您的数据集中1.1开阔环境定位的时候，发现固定率不足50%，在查看log的时候发现经常有类似如下的提示
.`Invalid ambiguity resolution: Total cost changes from 6.615e+00 to 6.655e+00.`
这样可能会导致很多模糊度没有固定，请问是我哪里的配置存在问题么，还是可以把这个地方的阈值松开让他去尝试固定

**Comment by chichengcn** [comment]
感谢认可！

其实TC和RRR算法都有这样的问题，不过虽然有一些模糊度不能固定，固定率相比于纯RTK偏低，但定位解精度满足固定解精度的历元数还是会比纯RTK高，因为窗内总会有固定了的历元。

不过的确，加入了INS或者相机之后，会因为“Total cost changes”的那个判定阈值，导致很多模糊度被认定为不合法的固定，这算是目前算法的一个BUG，虽然不影响精度，但在理论上的确不合理。目前算法对RTK固定是否合法的判定设计还是比较简单，可以考虑做一些更严谨的判定。

**Comment by lizhengnss** [comment]
感谢回复！
我是不是可以这么理解：虽然当先历元没有固定，但考虑到窗口中其他历元是固定解，所以当前历元由于IMU或视觉的帧间约束信息，仍然是一个比较高的精度。

**Comment by chichengcn** [comment]
嗯，是的。

**Comment by lizhengnss** [comment]
感谢池博回复，再次给您的工作点赞！
