### ISSUE TITLE
PPP/IMU TC如何使用

### ISSUE THREAD

**Issue by AnthonyCR68** [chichengcn/gici-open#34]
感谢更新PPP/IMU紧组合模式，谢谢您的持续工作
在这里有几个问题想想问一下您：
1.能否提供PPP/IMU TC的配置文件
2.会更新PPP/IMU LC模式吗？
3.看到您源代码中有PPP/IMU/Camera RRR模式的字段，大概什么时候可以更新此模式
再次感谢您对GICI-LIB的开发以及持续更新，辛苦啦。

**Comment by AnthonyCR68** [comment]
另外还有一个问题麻烦问一下您：manual中会更新PPP/IMU TC部分的说明吗。谢谢

**Comment by chichengcn** [comment]
感谢认可，
1. PPP/IMU TC配置文件已上传。
2. PPP/IMU LC模式等同于GNSS/IMU LC模式，这个模式一直有。只需要修改LC模式配置文件中gnss算法类型，即可实现各类LC算法。
3. PPP的RRR模式，后面我们这边有新的测试需求的话，会实现一下，可能在半年以内。不过，按照我们的设计初衷，我们的软件是高度模块化和面向对象的，通过我们的基类，去实现各种松、紧组合算法都比较容易，我们目前实现的算法都只是示例。
4. 我们觉得没有更新manual的必要性，因为PPP/IMU TC中的图结构部分与RTK/IMU TC并无明显区别，其中的PPP部分也与PPP-only算法没有明显区别，只需要参考这两部分内容即可。

**Comment by AnthonyCR68** [comment]
好的感谢回复，您的软件设计的非常好。祝您工作顺利
