### ISSUE TITLE
星历问题

### ISSUE THREAD

**Issue by michaelnbk** [chichengcn/gici-open#35]
您好：
  我想请教一下，(ephemeris->eph = (eph_t  *)malloc(sizeof(eph_t) * MAXSAT * 2))为什么要申请两倍的内存空间？是为了存储前后两个历元的星历数据还是其他用途？
期待您的回复，感谢！

**Comment by chichengcn** [comment]
是的，两倍空间是为了存储前后两个星历周期的星历数据。

input_rtcm2函数就是对rtcm2数据流的解码，根据rtcm数据协议的定义，一包数据可以包含多颗卫星的观测，但只能包含一颗卫星的星历。此外，rtcm电文还定义了其他类型的数据，比如基站坐标、SSR改正数等。详情请参考rtcm官方文档，或者源代码。
