### ISSUE TITLE
Build with ROS报错

### ISSUE THREAD

**Issue by lihua1981** [chichengcn/gici-open#47]
1. 参照说明2.2 Build with ROS，运行
catkin_make -DCMAKE_BUILD_TYPE=Release
2. 提示如下错误
[ 70%] Building CXX object gici/CMakeFiles/gici_ros_main.dir/src/gici_ros_main.cpp.o
In file included from /home/code/gici-open-master/ros_wrapper/src/gici/include/gici/ros_interface/ros_node_handle.h:18,
                 from /home/code/gici-open-master/ros_wrapper/src/gici/src/gici_ros_main.cpp:11:
/home/code/gici-open-master/ros_wrapper/src/gici/include/gici/ros_interface/ros_stream.h:21:10: fatal error: gici_ros/GlonassEphemeris.h: No such file or directory
   21 | #include <gici_ros/GlonassEphemeris.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [gici/CMakeFiles/gici_ros_main.dir/build.make:63: gici/CMakeFiles/gici_ros_main.dir/src/gici_ros_main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:620: gici/CMakeFiles/gici_ros_main.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j1 -l1" failed
3. 查看源码，发现ros_stream.h中有如下代码，但源码中却没有相关.h文件
#include <gici_ros/GlonassEphemeris.h>
#include <gici_ros/GnssAntennaPosition.h>
#include <gici_ros/GnssEphemerides.h>
#include <gici_ros/GnssIonosphereParameter.h>
#include <gici_ros/GnssObservations.h>
#include <gici_ros/GnssSsrCodeBiases.h>
#include <gici_ros/GnssSsrPhaseBiases.h>
#include <gici_ros/GnssSsrEphemerides.h>

期待您的回复，谢谢！

**Comment by chichengcn** [comment]
这些头文件源自ROS的自定义topic功能，其定义在[msg](https://github.com/chichengcn/gici-open/tree/master/ros_wrapper/src/gici/msg)文件夹。正常情况下，在catkin_make时，ros会先编译msg，而后再编译用户代码，你可能因为某种原因导致ros并没有编译msg。你可以考虑删掉build和devel文件夹再编译试一试，不行的话上网按照我上面描述的大致问题查一下看看。
