### ISSUE TITLE
Long optimize time in ceres-solver

### ISSUE THREAD

**Issue by 222233tommy** [chichengcn/gici-open#54]
Hi, Mr. Chi. Thank you for keeping this project updated.
I have found that the optimizing time of GNSS update (0.2 seconds) is much longer than the Vision update (0.07 seconds) in RTK-RRR mode. Could it be related to the C++ templates used in GNSS error, or errors of initial states in the factor graph? Looking forward to your reply. Thanks !!

**Comment by chichengcn** [comment]
The GNSS update and vision update optimizes the same LSQ problem, so their update time should be similar. The reason why the GNSS update takes longer time is that we need to conduct ambiguity resolution (AR) during this period. AR needs graph to compute the covariance of ambiguity parameters, feed them into an integer LSQ problem, constraint the solved ambiguity back into graph, and re-estimate. So the time-consuming is foreseeable.
