### ISSUE TITLE
Open-sky，RTK-TC固定率较低，RTK不固定的问题

### ISSUE THREAD

**Issue by shaoxiaodong92** [chichengcn/gici-open#58]
您好，为什么1.1是Open-sky的数据，但是固定率很低呢 ？只有约55%
![image](https://github.com/user-attachments/assets/cebe9c08-b623-43f1-af42-601fbc9f001f)

**Comment by shaoxiaodong92** [comment]
使用pseudo_real_time_estimation_RTK.yaml进行测试，发现全是浮点解，没有固定解。这和Open-sky这种场景有点预期不符，是我哪里需要配置设置一下，或者配置设置错了吗 ？
![image](https://github.com/user-attachments/assets/252ad792-f0c3-4dd9-93f5-2814859a4d23)

**Comment by shaoxiaodong92** [comment]
看了下论文中数据1.1的精度，感觉和线上的代码效果不一致？
![image](https://github.com/user-attachments/assets/eba169f7-ea7c-4dd4-a5d8-73a3c72c48e3)

**Comment by melonedo** [comment]
请问是确认效果不一致吗，还是有参数不同
