### ISSUE TITLE
Compile ERROR under Arch linux: gici/gnss/phase_bias.h:26:15: error: use of deleted function ‘std::unordered_map

### ISSUE THREAD

**Issue by yinflying** [chichengcn/gici-open#7]
solution:

add `include <string>` in file `code_bias.h` and `phase_bias.h`

**Comment by yinflying** [comment]
And will get `opencv` link error,

should install `vtk` ,  `hdf5`,  `glew`  lib

**Comment by chichengcn** [comment]
It seems that you have already solved this problem?
