### ISSUE TITLE
About the gnss/imu initializer

### ISSUE THREAD

**Issue by nwpuclydewang** [chichengcn/gici-open#8]
Sorry to disturb.I'm doubt that whether the gnss/imu initializer can be used while the carrier is  in motion. Hope that you can solve my problem.THANKS.

**Comment by chichengcn** [comment]
Sure. For example, our dataset 4.2 was in motion initially, and the initialization worked well.

**Comment by nwpuclydewang** [comment]
OK.How can i use gici-lib while playing my own rosbag?Just rectify the yaml is ok?

**Comment by chichengcn** [comment]
Yes, just rectify the yaml file. See our example configurations and documentation for details.
