### ISSUE TITLE
Maybe System error!`

### ISSUE THREAD

**Issue by michaelnbk** [chichengcn/gici-open#9]
Hi, Dr Chi:
I found that there may exist some system error in your datasets, for example:
![PDF_and_CDF_of_Position_Error](https://github.com/chichengcn/gici-open/assets/20315245/2d11396f-09a5-4b18-93ad-52865e56614c)
and
![CDF_and_PDF_of_3D_Error](https://github.com/chichengcn/gici-open/assets/20315245/d429baa4-85a5-4564-bc12-96d7c4f4c43c)
Do I make some mistakes when dealing with data?

And some data will end without optimization.

**Comment by michaelnbk** [comment]
Sorry for last question, I forgot to change date in yaml!!!

**Comment by chichengcn** [comment]
Okay.
